# Generated by Django 4.2.16 on 2025-01-20 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_restaurant_updated_on'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpeningTime',
            new_name='Time',
        ),
    ]
