# Generated by Django 4.2.16 on 2025-01-20 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_visit_produce_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
