# Generated by Django 4.2.18 on 2025-01-30 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_restaurant_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='num_tables',
        ),
    ]
