# Generated by Django 4.2.16 on 2024-10-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True),
        ),
    ]
