# Generated by Django 4.2.16 on 2025-01-14 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('book', '0002_alter_booking_special_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_booking', to='home.restaurant'),
        ),
    ]
