# Generated by Django 4.2.16 on 2025-01-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_booking_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'Confirmed'), (1, 'Declined')], default=0),
        ),
    ]
