# Generated by Django 4.2.18 on 2025-01-31 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_restaurant_num_tables'),
        ('book', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(default='2025-01-31 13:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(default='2025-01-31 12:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='party_size',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.PositiveIntegerField()),
                ('restaurant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_table', to='home.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='table_booking', to='book.diningtable'),
            preserve_default=False,
        ),
    ]
