# Generated by Django 4.2.18 on 2025-02-06 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_booking_end_time_booking_start_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date', 'time']},
        ),
    ]
