# Generated by Django 4.2.16 on 2025-01-19 14:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_created_on_menu_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='type_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
