# Generated by Django 4.2.16 on 2025-01-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_type_type_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
